spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kgitforge?currentSchema=gitforge
    username: mvanbrummen
    password: ""
  thymeleaf:
    cache: false
  flyway:
    schemas: gitforge

gitforge:
  home: ${GITFORGE_HOME:.gitforge}
  ssh:
    port: 8008